services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - app_code:/var/www/html:ro
    depends_on:
      - php
    networks:
      - appnet
  
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    command: ["php-fpm", "-F"]
    env_file:
      - .env
    volumes:
      - app_code:/var/www/html
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html
          initial_sync: true
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: camagru
      POSTGRES_USER: camagru
      POSTGRES_PASSWORD: camagru
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - appnet

volumes:
  postgres_data:
  app_code:

networks:
  appnet:
